#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 230

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "OQGr9/ormnjr"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 5

#define RGB_MATRIX_STARTUP_SPD 60

